### ISSUE TITLE
你好 

### ISSUE THREAD

**Issue by z24500112** [iii-bolinli/Beacon-Content#1]
我使用你們的dome的程式
出現了以下錯誤訊息

04-22 03:11:22.782 17898-17898/iii.org.tw.pushmessage E/AndroidRuntime: FATAL EXCEPTION: main
                                                                        Process: iii.org.tw.pushmessage, PID: 17898
                                                                        java.lang.NoClassDefFoundError: Failed resolution of: Lcom/akr/android/beacon/CrytoCannex;
                                                                            at tw.org.iii.beaconcontentsdk.BeaconContentService$3.onLeScan(Unknown Source)
                                                                            at android.bluetooth.BluetoothAdapter$2.onScanResult(BluetoothAdapter.java:2354)
                                                                            at android.bluetooth.le.BluetoothLeScanner$BleScanCallbackWrapper$1.run(BluetoothLeScanner.java:355)
                                                                            at android.os.Handler.handleCallback(Handler.java:739)
                                                                            at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                            at android.os.Looper.loop(Looper.java:234)
                                                                            at android.app.ActivityThread.main(ActivityThread.java:5526)
                                                                            at java.lang.reflect.Method.invoke(Native Method)
                                                                            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                                                            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
                                                                         Caused by: java.lang.ClassNotFoundException: Didn't find class "com.akr.android.beacon.CrytoCannex" on path: DexPathList[[dex file "/data/data/iii.org.tw.pushmessage/files/instant-run/dex/slice-support-annotations-23.4.0_6e6e7b431586272ebe2f8764b9c3add9e497776b-classes.dex", dex file "/data/data/iii.org.tw.pushmessage/files/instant-run/dex/slice-slice_9-classes.dex", dex file "/data/data/iii.org.tw.pushmessage/files/instant-run/dex/slice-slice_8-classes.dex", dex file "/data/data/iii.org.tw.pushmessage/files/instant-run/dex/slice-slice_7-classes.dex", dex file "/data/data/iii.org.tw.pushmessage/files/instant-run/dex/slice-slice_6-classes.dex", dex file "/data/data/iii.org.tw.pushmessage/files/instant-run/dex/slice-slice_5-classes.dex", dex file "/data/data/iii.org.tw.pushmessage/files/instant-run/dex/slice-slice_4-classes.dex", dex file "/data/data/iii.org.tw.pushmessage/files/instant-run/dex/slice-slice_3-classes.dex", dex file "/data/data/iii.org.tw.pushmessage/files/instant-run/dex/slice-slice_2-classes.dex", dex file "/data/data/iii.org.tw.pushmessage/files/instant-run/dex/slice-slice_1-classes.dex", dex file "/data/data/iii.org.tw.pushmessage/files/instant-run/dex/slice-slice_0-classes.dex", dex file "/data/data/iii.org.tw.pushmessage/files/instant-run/dex/slice-picasso-2.5.2_13d24420b9ee1a979ff5b6e4c837b1a92c23f2f6-classes.dex", dex file "/data/data/iii.org.tw.pushmessage/files/instant-run/dex/slice-internal_impl-23.4.0_7044a9508a4de05535ad680781db4a5107f5afa9-classes.dex", dex file "/data/data/iii.org.tw.pushmessage/files/instant-run/dex/slice-intermediates-exploded-aar-beaconcontentsdk_v2.6_withLog_16646c1a29e2dc039f4fb9fe3666483ad29539ce-classes.dex", dex file "/data/data/iii.org.tw.pushmessage/files/instant-run/dex/slice-intermediates-exploded-aar-beaconcontentsdk_v2.6_11945fae77855b83d3c4f88aefc464130c6174ea-classes.dex", dex file "/data/data/iii.org.tw.pushmessage/files/instant-run/dex/slice-intermediates-exploded-aar-beaconcontentsdk_v2.5_withLog_7b5a7c4aad52512108f313f5c35241f20f32642e-classes.dex", dex file "/data/data/iii.org.tw.pushmessage/files/instant-run/dex/slice-instant-run_f1a2c0bc199c84ca7d6e545d7a26862780c970a9-classes.dex", dex file "/data/data/iii.org.tw.pushmessage/files/instant-run/dex/slice-instant-run-bootstrap_0adce32483fa06629fbda1e566a3dd3ac705eb3f-classes.dex", dex file "/data/data/iii.org.tw.pushmessage/files/instant-run/dex/slice-gson-2.6.2_3d0d78f6e6c6cc614a583f0edcee242571667853-classes.dex", dex file "/data/data/iii.org.tw.pushmessage/files/instant-run/dex/slice-com.android.support-support-vector-drawable-23.4.0_974c47f821d8aa38c309870a64fb6e0c2b468363-classes.dex", dex file "/data/data/iii.org.tw.pushmessage/files/instant-run/dex/slice-com.android.support-support-v4-23.4.0_34fb0f17fa24d367be2c1581db769ba64dc80e9f-classes.dex", dex file "/data/data/iii.org.tw.pushmessage/files/instant-run/dex/slice-com.android.support-appcompat-v7-23.4.0_a98fb29e09bef27f8508e66724c1672810651810-classes.dex", dex file "/data/data/iii.org.tw.pushmessage/files/instant-run/dex/slice-com.android.support-animated-vector-drawable-23.4.0_e667ba69f0bd358d960cc2de1d251d474e76a7ff-classes.dex", dex file "/data/data/iii.org.tw.pushmessage/files/instan

**Comment by iii-bolinli** [comment]
這個錯誤我們已經發現是新版本的 Bug 目前建議先使用 2.5 版

造成不便敬請見諒

謝謝

**Comment by z24500112** [comment]
那我在log.d發現這段
D/BluetoothLeScanner: onScanResult() - ScanResult{mDevice=E0:E5:CF:32:3C:72, mScanRecord=ScanRecord [mAdvertiseFlags=6, mServiceUuids=null, mManufacturerSpecificData={76=[2, 21, -26, -123, -114, -67, 59, -67, 65, -40, -121, 68, 116, 43, -42, -91, 36, -47, 14, 15, 7, -83, -70]}, mServiceData={00000100-0000-1000-8000-00805f9b34fb=[9, -93, 36]}, mTxPowerLevel=-2147483648, mDeviceName=WBeacon], mRssi=-99, mTimestampNanos=117831282794872}
抓到beacon之後程式閃退 這是什麼問題?
D/AndroidRuntime: Shutting down VM

**Comment by iii-bolinli** [comment]
這應該與抓到 Beacon 之後所做的事情有關，方便將 `ResultReceiver ` 中的內容貼上來嗎？

**Comment by z24500112** [comment]
此問題我以解決 我開新的專案，將AAR導入 在新增你們的物件 就解決了
謝謝
